import type { Metadata } from "next";
import "./globals.css";
import Nav from "./components/Nav";
import CustomCursor from "./components/CustomCursor";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Nav />
      <body
        className={`antialiased`}
        style={{ backgroundColor: "var(--bg-color, #020617)" }}
      >
        <CustomCursor />
        {children}
      </body>
    </html>
  );
}
