import type { Metadata } from "next";
import "./globals.css";
import Nav from "./components/Nav";
import Footer from "./components/Footer";
import { Toaster } from "@/components/ui/sonner";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Toaster />


      <Nav />
 
      
      <body
        className={`antialiased`}
        style={{ backgroundColor: "var(--bg-color, #020617)" }}
      >
        
        {children}
        <Footer />
      </body>
    </html>
  );
}
